### registration via sms
POST localhost:8081/auth/phone
Content-Type: application/json

{
  "name": "Aslbek",
  "surname": "Norqulov",
  "phone": "+998991205577",
  "password": "@Aslbek1202"
}

### check profile via sms
POST localhost:8080/auth/verification
Content-Type: application/json

{
  "phone": "+998991205577",
  "code": "75696"
}

### Login Admin
POST localhost:8081/auth/login
Content-Type: application/json
Accept-Language: UZ

{
  "phone": "+998991205577",
  "password": "@Aslbek1202"
}

